/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Permutation */

#ifndef _Included_Permutation
#define _Included_Permutation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Permutation
 * Method:    printPermutation
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_Permutation_printPermutation
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
