/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class arraypermutations_Permutations */

#ifndef _Included_arraypermutations_Permutations
#define _Included_arraypermutations_Permutations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     arraypermutations_Permutations
 * Method:    call
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_arraypermutations_Permutations_call
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
