/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Permutations */

#ifndef _Included_Permutations
#define _Included_Permutations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Permutations
 * Method:    printPermutations
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_Permutations_printPermutations
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
