/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rohit_jni_Permutation */

#ifndef _Included_com_rohit_jni_Permutation
#define _Included_com_rohit_jni_Permutation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rohit_jni_Permutation
 * Method:    permute
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_rohit_jni_Permutation_permute
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
